/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PromocodeImport } from './routes/promocode'
import { Route as ProductImport } from './routes/product'
import { Route as OrdersImport } from './routes/orders'
import { Route as AdditemImport } from './routes/additem'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PromocodeRoute = PromocodeImport.update({
  id: '/promocode',
  path: '/promocode',
  getParentRoute: () => rootRoute,
} as any)

const ProductRoute = ProductImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRoute,
} as any)

const OrdersRoute = OrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRoute,
} as any)

const AdditemRoute = AdditemImport.update({
  id: '/additem',
  path: '/additem',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/additem': {
      id: '/additem'
      path: '/additem'
      fullPath: '/additem'
      preLoaderRoute: typeof AdditemImport
      parentRoute: typeof rootRoute
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersImport
      parentRoute: typeof rootRoute
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductImport
      parentRoute: typeof rootRoute
    }
    '/promocode': {
      id: '/promocode'
      path: '/promocode'
      fullPath: '/promocode'
      preLoaderRoute: typeof PromocodeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/additem': typeof AdditemRoute
  '/orders': typeof OrdersRoute
  '/product': typeof ProductRoute
  '/promocode': typeof PromocodeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/additem': typeof AdditemRoute
  '/orders': typeof OrdersRoute
  '/product': typeof ProductRoute
  '/promocode': typeof PromocodeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/additem': typeof AdditemRoute
  '/orders': typeof OrdersRoute
  '/product': typeof ProductRoute
  '/promocode': typeof PromocodeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/additem' | '/orders' | '/product' | '/promocode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/additem' | '/orders' | '/product' | '/promocode'
  id: '__root__' | '/' | '/additem' | '/orders' | '/product' | '/promocode'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdditemRoute: typeof AdditemRoute
  OrdersRoute: typeof OrdersRoute
  ProductRoute: typeof ProductRoute
  PromocodeRoute: typeof PromocodeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdditemRoute: AdditemRoute,
  OrdersRoute: OrdersRoute,
  ProductRoute: ProductRoute,
  PromocodeRoute: PromocodeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/additem",
        "/orders",
        "/product",
        "/promocode"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/additem": {
      "filePath": "additem.jsx"
    },
    "/orders": {
      "filePath": "orders.jsx"
    },
    "/product": {
      "filePath": "product.jsx"
    },
    "/promocode": {
      "filePath": "promocode.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
